In [4]:
# Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

print("=== СОЗДАНИЕ МАССИВОВ ===\n")

# Создание массива из обычного списка Python
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)
print("Массив из списка:", array_from_list)

# Создание двумерного массива из вложенного списка
matrix_data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matrix = np.array(matrix_data)
print("Двумерный массив:")
print(matrix)

# Создание массива, заполненного нулями
zeros_array = np.zeros(5)
print("Массив из нулей:", zeros_array)

# Создание двумерного массива, заполненного единицами
ones_matrix = np.ones((3, 4))
print("Массив 3x4 из единиц:")
print(ones_matrix)

# Создание массива с последовательностью чисел
range_array = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив от 0 до 10 с шагом 2:", range_array)

# Создание массива с равномерно распределенными значениями
linspace_array = np.linspace(0, 1, 5)  # 5 значений от 0 до 1
print("5 значений от 0 до 1:", linspace_array)

print("\n=== АТРИБУТЫ МАССИВОВ ===\n")

# Демонстрация атрибутов массива
print("Исходный массив:")
print(matrix)
print("Форма массива (shape):", matrix.shape)  # Размерность массива
print("Тип данных (dtype):", matrix.dtype)    # Тип элементов массива
print("Количество измерений (ndim):", matrix.ndim)  # Число осей
print("Общее количество элементов (size):", matrix.size)

print("\n=== ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===\n")

# Одномерный массив для демонстрации индексирования
arr_1d = np.array([10, 20, 30, 40, 50, 60])
print("Одномерный массив:", arr_1d)

# Получение отдельного элемента
print("Элемент с индексом 0:", arr_1d[0])
print("Элемент с индексом 2:", arr_1d[2])
print("Последний элемент:", arr_1d[-1])

# Срезы в одномерном массиве
print("Срез [1:4]:", arr_1d[1:4])      # элементы с 1 по 3
print("Срез [::2]:", arr_1d[::2])      # каждый второй элемент
print("Срез [3:]:", arr_1d[3:])        # все элементы с 3 до конца

# Двумерный массив для демонстрации
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nДвумерный массив:")
print(arr_2d)

# Индексирование в двумерном массиве
print("Элемент [0,1]:", arr_2d[0, 1])     # строка 0, столбец 1
print("Элемент [2,2]:", arr_2d[2, 2])     # строка 2, столбец 2

# Срезы в двумерном массиве
print("Первая строка:", arr_2d[0, :])     # вся строка 0
print("Последний столбец:", arr_2d[:, -1]) # весь последний столбец
print("Подмассив 2x2:")
print(arr_2d[:2, :2])                     # первые 2 строки и 2 столбца

print("\n=== ВЕКТОРНЫЕ ОПЕРАЦИИ ===\n")

# Создание двух массивов для операций
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print("Массив a:", a)
print("Массив b:", b)

# Поэлементные арифметические операции
print("a + b =", a + b)      # Поэлементное сложение
print("a - b =", a - b)      # Поэлементное вычитание
print("a * b =", a * b)      # Поэлементное умножение
print("b / a =", b / a)      # Поэлементное деление
print("a ** 2 =", a ** 2)    

# Операции с вещественными числами
float_array = np.array([1.5, 2.5, 3.5, 4.5])
print("\nМассив с float:", float_array)
print("Умножение на скаляр:", float_array * 2)
print("Прибавление скаляра:", float_array + 10)

print("\n=== БАЗОВАЯ СТАТИСТИКА ===\n")

# Создание массива для статистических вычислений
stats_array = np.array([2, 5, 8, 3, 7, 1, 9, 4, 6])
print("Массив для статистики:", stats_array)

# Базовые статистические функции
print("Среднее значение (mean):", np.mean(stats_array))
print("Медиана (median):", np.median(stats_array))
print("Стандартное отклонение (std):", np.std(stats_array))
print("Дисперсия (var):", np.var(stats_array))
print("Минимальное значение (min):", np.min(stats_array))
print("Максимальное значение (max):", np.max(stats_array))
print("Сумма всех элементов (sum):", np.sum(stats_array))

# Статистика по осям в двумерном массиве
matrix_stats = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nМатрица для статистики:")
print(matrix_stats)
print("Среднее по столбцам:", np.mean(matrix_stats, axis=0))
print("Среднее по строкам:", np.mean(matrix_stats, axis=1))
print("Сумма по столбцам:", np.sum(matrix_stats, axis=0))

=== СОЗДАНИЕ МАССИВОВ ===

Массив из списка: [1 2 3 4 5]
Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив 3x4 из единиц:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Массив от 0 до 10 с шагом 2: [0 2 4 6 8]
5 значений от 0 до 1: [0.   0.25 0.5  0.75 1.  ]

=== АТРИБУТЫ МАССИВОВ ===

Исходный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма массива (shape): (3, 3)
Тип данных (dtype): int64
Количество измерений (ndim): 2
Общее количество элементов (size): 9

=== ИНДЕКСИРОВАНИЕ И СРЕЗЫ ===

Одномерный массив: [10 20 30 40 50 60]
Элемент с индексом 0: 10
Элемент с индексом 2: 30
Последний элемент: 60
Срез [1:4]: [20 30 40]
Срез [::2]: [10 30 50]
Срез [3:]: [40 50 60]

Двумерный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [0,1]: 2
Элемент [2,2]: 9
Первая строка: [1 2 3]
Последний столбец: [3 6 9]
Подмассив 2x2:
[[1 2]
 [4 5]]

=== ВЕКТОРНЫЕ ОПЕРАЦИИ ===

Массив a: [1 2 3 4]
Массив b: [5 6 7 8]
a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
